// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC550HjpzlZ2TtM_-g2_FRhR3yFNBi-edA',
    appId: '1:765714450974:web:745c07902789c8507dbc0f',
    messagingSenderId: '765714450974',
    projectId: 'eventify-flutter',
    authDomain: 'eventify-flutter.firebaseapp.com',
    storageBucket: 'eventify-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbp1UIdOHpLNnykWaIBb0T6AGSqEXAVG4',
    appId: '1:765714450974:android:e748b8ff057ea7477dbc0f',
    messagingSenderId: '765714450974',
    projectId: 'eventify-flutter',
    storageBucket: 'eventify-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLfESKeaUgaRyFiUPPBfpUvFldyj3bckU',
    appId: '1:765714450974:ios:effbb8b7d4224ebb7dbc0f',
    messagingSenderId: '765714450974',
    projectId: 'eventify-flutter',
    storageBucket: 'eventify-flutter.firebasestorage.app',
    iosBundleId: 'com.example.eventify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLfESKeaUgaRyFiUPPBfpUvFldyj3bckU',
    appId: '1:765714450974:ios:effbb8b7d4224ebb7dbc0f',
    messagingSenderId: '765714450974',
    projectId: 'eventify-flutter',
    storageBucket: 'eventify-flutter.firebasestorage.app',
    iosBundleId: 'com.example.eventify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC550HjpzlZ2TtM_-g2_FRhR3yFNBi-edA',
    appId: '1:765714450974:web:52f71d32dee18ae77dbc0f',
    messagingSenderId: '765714450974',
    projectId: 'eventify-flutter',
    authDomain: 'eventify-flutter.firebaseapp.com',
    storageBucket: 'eventify-flutter.firebasestorage.app',
  );
}
